bearer_token = '<ADD BEARER TOKEN HERE>'
consumer_key = '<ADD CONSUMER KEY HERE>'
consumer_secret = '<ADD CONSUMER SECRET HERE>'
access_token = '<ADD ACCESS TOKEN HERE>'
access_secret = '<ADD ACCESS SECRET HERE>'

# set path to workspace
workspace = r'<ADD WORKSPACE HERE>'

# set default CSV or XLSX file
default_file = '<ADD FILE NAME HERE>'

# create states dictionary that stores states using abbrev as key
states = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'DC': 'District of Columbia',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming'
}

# make sure certain populous US cities (and DC) are included directly
# initialize a cities dict with city names as keys and their respective state as the values
cities = {
    'NYC': 'New York',
    'New York City': 'New York',
    'Brooklyn': 'New York',
    'Manhattan': 'New York',
    'Bronx': 'New York',
    'Staten Island': 'New York',
    'Buffalo': 'New York',
    'WNY': 'New York',
    'Calif': 'California',
    'Cali': 'California',
    'Cal': 'California',
    'Los Angeles': 'California',
    'San Diego': 'California',
    'San Jose': 'California',
    'San Francisco': 'California',
    'San Fran': 'California',
    'SF': 'California',
    'SoCal': 'California',
    'Sacramento': 'California',
    'Long Beach': 'California',
    'Oakland': 'California',
    'Chicago': 'Illinois',
    'Chi': 'Illinois',
    'Chitown': 'Illinois',
    'Houston': 'Texas',
    'SA': 'Texas',
    'San Antonio': 'Texas',
    'Dallas': 'Texas',
    'Frisco': 'Texas',
    'Phoenix': 'Arizona',
    'Tuscon': 'Arizona',
    'Philly': 'Pennsylvania',
    'Philadelphia': 'Pennsylvania',
    'Pittsburgh': 'Pennsylvania',
    'Honolulu': 'Hawaii',
    'Hawai\'i': 'Hawaii',
    'Hawaiian': 'Hawaii',
    'Baltimore': 'Maryland',
    'Atlanta': 'Georgia',
    'ATL': 'Georgia',
    'Boston': 'Massachusetts',
    'Seattle': 'Washington',
    'Miami': 'Florida',
    'MIA': 'Florida',
    'Orlando': 'Florida',
    'Tampa': 'Florida',
    'Tampa Bay': 'Florida',
    'Tallahassee': 'Florida',
    'New Orleans': 'Louisiana',
    'LA Gulf Coast': 'Louisiana',
    'Minneapolis': 'Minnesota',
    'Omaha': 'Nebraska',
    'Vegas': 'Nevada',
    'LV': 'Nevada',
    'Sin City': 'Nevada',
    'Reno': 'Nevada',
    'Charlotte': 'North Carolina',
    'Tuscaloosa': 'Alabama',
    'Milwaukee': 'Wisconsin',
    'Memphis': 'Tennessee',
    'Louisville': 'Kentucky',
    'Cleveland': 'Ohio',
    'Albuquerque': 'New Mexico',
    'Denver': 'Colorado',
    'Detroit': 'Michigan',
    'Kansas City': 'Missouri',
    'St Louis': 'Missouri',
    'STL': 'Missouri',
    'Saint Louis': 'Missouri',
}

# create area_codes dictionary
area_codes = {
	'201': 'New Jersey',
	'202': 'District of Columbia',
	'203': 'Connecticut',
	'205': 'Alabama',
	'206': 'Washington',
	'207': 'Maine',
	'208': 'Idaho',
	'209': 'California',
	'210': 'Texas',
	'212': 'New York',
	'213': 'California',
	'214': 'Texas',
	'215': 'Pennsylvania',
	'216': 'Ohio',
	'217': 'Illinois',
	'218': 'Minnesota',
	'219': 'Indiana',
	'220': 'Ohio',
	'223': 'Pennsylvania',
	'224': 'Illinois',
	'225': 'Louisiana',
	'228': 'Mississippi',
	'229': 'Georgia',
	'231': 'Michigan',
	'234': 'Ohio',
	'239': 'Florida',
	'240': 'Maryland',
	'248': 'Michigan',
	'251': 'Alabama',
	'252': 'North Carolina',
	'253': 'Washington',
	'254': 'Texas',
	'256': 'Alabama',
	'260': 'Indiana',
	'262': 'Wisconsin',
	'267': 'Pennsylvania',
	'269': 'Michigan',
	'270': 'Kentucky',
	'272': 'Pennsylvania',
	'276': 'Virginia',
	'279': 'California',
	'281': 'Texas',
	'301': 'Maryland',
	'302': 'Delaware',
	'303': 'Colorado',
	'304': 'West Virginia',
	'305': 'Florida',
	'307': 'Wyoming',
	'308': 'Nebraska',
	'309': 'Illinois',
	'310': 'California',
	'312': 'Illinois',
	'313': 'Michigan',
	'314': 'Missouri',
	'315': 'New York',
	'316': 'Kansas',
	'317': 'Indiana',
	'318': 'Louisiana',
	'319': 'Iowa',
	'320': 'Minnesota',
	'321': 'Florida',
	'323': 'California',
	'325': 'Texas',
	'326': 'Ohio',
	'330': 'Ohio',
	'331': 'Illinois',
	'332': 'New York',
	'334': 'Alabama',
	'336': 'North Carolina',
	'337': 'Louisiana',
	'339': 'Massachusetts',
	'341': 'California',
	'346': 'Texas',
	'347': 'New York',
	'351': 'Massachusetts',
	'352': 'Florida',
	'360': 'Washington',
	'361': 'Texas',
	'364': 'Kentucky',
	'380': 'Ohio',
	'385': 'Utah',
	'386': 'Florida',
	'401': 'Rhode Island',
	'402': 'Nebraska',
	'404': 'Georgia',
	'405': 'Oklahoma',
	'406': 'Montana',
	'407': 'Florida',
	'408': 'California',
	'409': 'Texas',
	'410': 'Maryland',
	'412': 'Pennsylvania',
	'413': 'Massachusetts',
	'414': 'Wisconsin',
	'415': 'California',
	'417': 'Missouri',
	'419': 'Ohio',
	'423': 'Tennessee',
	'424': 'California',
	'425': 'Washington',
	'430': 'Texas',
	'432': 'Texas',
	'434': 'Virginia',
	'435': 'Utah',
	'440': 'Ohio',
	'442': 'California',
	'443': 'Maryland',
	'448': 'Florida',
	'458': 'Oregon',
	'463': 'Indiana',
	'469': 'Texas',
	'470': 'Georgia',
	'475': 'Connecticut',
	'478': 'Georgia',
	'479': 'Arkansas',
	'480': 'Arizona',
	'484': 'Pennsylvania',
	'501': 'Arkansas',
	'502': 'Kentucky',
	'503': 'Oregon',
	'504': 'Louisiana',
	'505': 'New Mexico',
	'507': 'Minnesota',
	'508': 'Massachusetts',
	'509': 'Washington',
	'510': 'California',
	'512': 'Texas',
	'513': 'Ohio',
	'515': 'Iowa',
	'516': 'New York',
	'517': 'Michigan',
	'518': 'New York',
	'520': 'Arizona',
	'530': 'California',
	'531': 'Nebraska',
	'534': 'Wisconsin',
	'539': 'Oklahoma',
	'540': 'Virginia',
	'541': 'Oregon',
	'551': 'New Jersey',
	'557': 'Missouri',
	'559': 'California',
	'561': 'Florida',
	'562': 'California',
	'563': 'Iowa',
	'564': 'Washington',
	'567': 'Ohio',
	'570': 'Pennsylvania',
	'571': 'Virginia',
	'572': 'Oklahoma',
	'573': 'Missouri',
	'574': 'Indiana',
	'575': 'New Mexico',
	'580': 'Oklahoma',
	'585': 'New York',
	'586': 'Michigan',
	'601': 'Mississippi',
	'602': 'Arizona',
	'603': 'New Hampshire',
	'605': 'South Dakota',
	'606': 'Kentucky',
	'607': 'New York',
	'608': 'Wisconsin',
	'609': 'New Jersey',
	'610': 'Pennsylvania',
	'612': 'Minnesota',
	'614': 'Ohio',
	'615': 'Tennessee',
	'616': 'Michigan',
	'617': 'Massachusetts',
	'618': 'Illinois',
	'619': 'California',
	'620': 'Kansas',
	'623': 'Arizona',
	'626': 'California',
	'628': 'California',
	'629': 'Tennessee',
	'630': 'Illinois',
	'631': 'New York',
	'636': 'Missouri',
	'640': 'New Jersey',
	'641': 'Iowa',
	'646': 'New York',
	'650': 'California',
	'651': 'Minnesota',
	'656': 'Florida',
	'657': 'California',
	'659': 'Alabama',
	'660': 'Missouri',
	'661': 'California',
	'662': 'Mississippi',
	'667': 'Maryland',
	'669': 'California',
	'678': 'Georgia',
	'680': 'New York',
	'681': 'West Virginia',
	'682': 'Texas',
	'701': 'North Dakota',
	'702': 'Nevada',
	'703': 'Virginia',
	'704': 'North Carolina',
	'706': 'Georgia',
	'707': 'California',
	'708': 'Illinois',
	'712': 'Iowa',
	'713': 'Texas',
	'714': 'California',
	'715': 'Wisconsin',
	'716': 'New York',
	'717': 'Pennsylvania',
	'718': 'New York',
	'719': 'Colorado',
	'720': 'Colorado',
	'724': 'Pennsylvania',
	'725': 'Nevada',
	'726': 'Texas',
	'727': 'Florida',
	'731': 'Tennessee',
	'732': 'New Jersey',
	'734': 'Michigan',
	'737': 'Texas',
	'740': 'Ohio',
	'743': 'North Carolina',
	'747': 'California',
	'754': 'Florida',
	'757': 'Virginia',
	'760': 'California',
	'762': 'Georgia',
	'763': 'Minnesota',
	'765': 'Indiana',
	'769': 'Mississippi',
	'770': 'Georgia',
	'772': 'Florida',
	'773': 'Illinois',
	'774': 'Massachusetts',
	'775': 'Nevada',
	'779': 'Illinois',
	'781': 'Massachusetts',
	'785': 'Kansas',
	'786': 'Florida',
	'801': 'Utah',
	'802': 'Vermont',
	'803': 'South Carolina',
	'804': 'Virginia',
	'805': 'California',
	'806': 'Texas',
	'808': 'Hawaii',
	'810': 'Michigan',
	'812': 'Indiana',
	'813': 'Florida',
	'814': 'Pennsylvania',
	'815': 'Illinois',
	'816': 'Missouri',
	'817': 'Texas',
	'818': 'California',
	'820': 'California',
	'826': 'Virginia',
	'828': 'North Carolina',
	'830': 'Texas',
	'831': 'California',
	'832': 'Texas',
	'838': 'New York',
	'839': 'South Carolina',
	'840': 'California',
	'843': 'South Carolina',
	'845': 'New York',
	'847': 'Illinois',
	'848': 'New Jersey',
	'850': 'Florida',
	'854': 'South Carolina',
	'856': 'New Jersey',
	'857': 'Massachusetts',
	'858': 'California',
	'859': 'Kentucky',
	'860': 'Connecticut',
	'862': 'New Jersey',
	'863': 'Florida',
	'864': 'South Carolina',
	'865': 'Tennessee',
	'870': 'Arkansas',
	'872': 'Illinois',
	'878': 'Pennsylvania',
	'901': 'Tennessee',
	'903': 'Texas',
	'904': 'Florida',
	'905': 'Ontario',
	'906': 'Michigan',
	'907': 'Alaska',
	'908': 'New Jersey',
	'909': 'California',
	'910': 'North Carolina',
	'912': 'Georgia',
	'913': 'Kansas',
	'914': 'New York',
	'915': 'Texas',
	'916': 'California',
	'917': 'New York',
	'918': 'Oklahoma',
	'919': 'North Carolina',
	'920': 'Wisconsin',
	'925': 'California',
	'927': 'Florida',
	'928': 'Arizona',
	'929': 'New York',
	'930': 'Indiana',
	'931': 'Tennessee',
	'932': 'West Virginia',
	'934': 'New York',
	'936': 'Texas',
	'937': 'Ohio',
	'938': 'Alabama',
	'940': 'Texas',
	'941': 'Florida',
	'945': 'Texas',
	'947': 'Michigan',
	'948': 'Virginia',
	'949': 'California',
	'951': 'California',
	'952': 'Minnesota',
	'954': 'Florida',
	'956': 'Texas',
	'959': 'Connecticut',
	'970': 'Colorado',
	'971': 'Oregon',
	'972': 'Texas',
	'973': 'New Jersey',
	'978': 'Massachusetts',
	'979': 'Texas',
	'980': 'North Carolina',
	'984': 'North Carolina',
	'985': 'Louisiana',
	'986': 'Idaho',
	'989': 'Michigan'
}