#!/bin/sh
# Name: tkm (tweetkeywordmapper)
# Author: Stephen C. Sanders <https://stephensanders.me>
# Description: wrapper for running tweetkeywordmapper python package

# display help information for program
helpFunc()
{
    echo ""
    echo "usage: ./tkm <parameter>\n"
    echo "Search/Import Tweet data from US states with a keyword, then map the count results\n"
    echo "optional parameters:"
    echo "search:\t search Twitter for Tweets containing a specific keyword, then map results"
    echo "read:\t import Tweet data from a CSV file, then map results"
    echo "counts:\t tally the total for each unique value of a specified field from a CSV file"
    echo "help:\t displays help information for this script\n"
    echo "- search and read will run mapper.py to map the results after state counts are determined.\n"
    exit 1
}

# handle parameter

# lack of parameter triggers the displaying of an error and the help info
if [ $# -eq "0" ]; then
    echo "ERROR - No parameter provided."
    helpFunc
    
    # run this if parameter is present
    else
        # display error and show help info if more than one parameter is specified
        if [ $# -gt "1" ]; then
            echo "ERROR - Too many parameters. Only 1 is allowed at most."
            helpFunc
            
            # run this if one parameter is present
            else
                # run search.py program when parameter is set to "search"
                if [ $1 = "search" ]; then
                    exec python3 tweetkeywordmapper -s
                    
                    # 
                    elif [ $1 = "read" ]; then
                        exec python3 tweetkeywordmapper -r
                    
                    # run counts.py program when parameter is set to "counts"
                    elif [ $1 = "counts" ]; then
                        exec python3 tweetkeywordmapper -c
                    
                    # display help info when parameter is set to "help"
                    elif [ $1 = "help" ]; then
                        helpFunc
                    
                    # display error and help info if the parameter is set to anything else
                    else
                        echo "ERROR - $1 is not a valid parameter value."
                        helpFunc
                fi
        fi
fi